import { useEffect, useMemo, useRef, useState } from 'react'
import { Clipboard, ClipboardCheck, Download, FileText, Printer, X } from 'lucide-react'
import type { AuditResult } from '../types'
import { buildReportHtml, reportFileName } from '../lib/reportHtml'

/** 클립보드에 복사할 요약 텍스트 생성 */
function buildSummaryText(audit: AuditResult): string {
  const domain = audit.url.replace(/^https?:\/\//, '').split('/')[0];
  const lines: string[] = [
    `📊 AI SEO 분석 결과 — ${domain}`,
    `🔗 ${audit.url}`,
    ``,
    `⭐ 종합 점수: ${audit.overallScore}/100`,
    `  Technical SEO : ${audit.technicalScore}`,
    `  ChatGPT Search: ${audit.chatGptSearchScore}`,
    `  GEO (AI 인용) : ${audit.academicGeoScore}`,
    `  E-E-A-T      : ${audit.eeatScore}`,
    `  Schema.org   : ${audit.schemaScore}`,
    `  Bing / AEO   : ${audit.bingScore}`,
  ];
  if (audit.seoFoundationScore !== undefined) {
    lines.push(`  SEO 기반 점수 : ${audit.seoFoundationScore}`);
  }
  if (audit.aiCitationReadinessScore !== undefined) {
    lines.push(`  AI 검색 가시성: ${audit.aiCitationReadinessScore}`);
  }
  lines.push(`  네이버 노출 기반: ${audit.naverScore ?? '미측정'}`);
  if (audit.summary) {
    lines.push(``, `💬 요약`, audit.summary);
  }
  if (audit.criticalIssues?.length) {
    lines.push(``, `🚨 주요 문제`, ...audit.criticalIssues.map((i) => `  • ${i}`));
  }
  if (audit.quickWins?.length) {
    lines.push(``, `⚡ 빠른 개선 항목`, ...audit.quickWins.map((q) => `  • ${q}`));
  }
  lines.push(``, `🕐 분석 일시: ${audit.lastScanned}`, `Generated by AI SEO Analyzer (SEOGEO)`);
  return lines.join('\n');
}

function reportBlob(html: string) {
  return new Blob([html], { type: 'text/html;charset=utf-8' })
}

export function ReportActions({ audit }: { audit: AuditResult }) {
  const [isOpen, setIsOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const previewHtml = useMemo(() => buildReportHtml(audit, { showToolbar: false }), [audit])
  const downloadHtml = useMemo(() => buildReportHtml(audit), [audit])

  useEffect(() => {
    if (!isOpen) return
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setIsOpen(false) }
    document.addEventListener('keydown', closeOnEscape)
    document.body.style.overflow = 'hidden'
    return () => {
      document.removeEventListener('keydown', closeOnEscape)
      document.body.style.overflow = ''
    }
  }, [isOpen])

  const print = () => {
    const reportWindow = iframeRef.current?.contentWindow
    if (!reportWindow) return
    reportWindow.focus()
    reportWindow.print()
  }

  const download = () => {
    const url = URL.createObjectURL(reportBlob(downloadHtml))
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = reportFileName(audit)
    anchor.style.display = 'none'
    document.body.appendChild(anchor)
    anchor.click()
    anchor.remove()
    window.setTimeout(() => URL.revokeObjectURL(url), 1_000)
  }

  const copySummary = async () => {
    try {
      await navigator.clipboard.writeText(buildSummaryText(audit))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // 클립보드 권한 없을 때 fallback
      const ta = document.createElement('textarea')
      ta.value = buildSummaryText(audit)
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      ta.remove()
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return <>
    <section className="v04-report-bar">
      <div><span><FileText size={17} /> HTML 보고서</span><p>분석 결과를 확인하고 PDF 또는 HTML로 저장하세요.</p></div>
      <div className="v04-report-actions">
        <button onClick={copySummary} title="결과 요약을 클립보드에 복사">
          {copied ? <ClipboardCheck size={15} /> : <Clipboard size={15} />}
          {copied ? '복사됨!' : '요약 복사'}
        </button>
        <button onClick={() => setIsOpen(true)}><FileText size={15} /> 보고서 보기</button>
        <button onClick={download}><Download size={15} /> HTML 저장</button>
      </div>
    </section>

    {isOpen && <div className="v04-report-modal" role="dialog" aria-modal="true" aria-label="SEO GEO 분석 보고서 미리보기" onMouseDown={event => { if (event.target === event.currentTarget) setIsOpen(false) }}>
      <div className="v04-report-window">
        <header>
          <div><strong>HTML 보고서 미리보기</strong><span>{audit.url.replace(/^https?:\/\//, '')}</span></div>
          <div>
            <button onClick={download}><Download size={15} /> HTML 저장</button>
            <button className="primary" onClick={print}><Printer size={15} /> PDF로 인쇄</button>
            <button className="close" onClick={() => setIsOpen(false)} aria-label="보고서 닫기"><X size={18} /></button>
          </div>
        </header>
        <iframe ref={iframeRef} title={`${audit.title} SEO GEO 보고서`} srcDoc={previewHtml} />
      </div>
    </div>}
  </>
}
